### ISSUE TITLE
Support multiple/named registrations and resolutions

### ISSUE THREAD

**Issue by psibernetic** [jonsequitur/PocketContainer#9]
My use case is a set of interfaces `IConnector` which are registered with a name each. I have a class `ConnectorResolver` with a dependency on `IEnumerable<IConnector>`, that dependency should be satisfiable.

**Comment by jonsequitur** [comment]
Do you need to resolve specific types by name, or are they always all resolved together? The latter is supported in a couple of different ways.

With the default `PocketContainer` behavior, you can register and resolve `IEnumerable<IConnector>` assuming it's practical to register all of the implementations up front. You could also discover them dynamically, something like this:

```csharp
            var implementations = Discover
                .ConcreteTypes()
                .DerivedFrom(typeof(IConnector));

            container.Register<IEnumerable<IConnector>>(c =>
                    implementations.Select(c.Resolve).Cast<IConnector>());
```

I recently added support for cumulative registrations as well, in order to provide the option of mimicking the behavior of `Microsoft.Extensions.DependencyInjection`. You can see that [here](https://github.com/jonsequitur/PocketContainer/tree/master/Pocket.Container.Behaviors.CumulativeRegistration), although I don't have a package published for it yet. This allows you to call register multiple times and then resolve all of the registered types via `IEnumerable<T>`.

```csharp
            var container = new PocketContainer();

            container.Register<IConnector>(c => new ConnectorOne());
            container.Register<IConnector>(c => new ConnectorTwo());

            var connectors = container.Resolve<IEnumerable<IConnector>>();

            connectors.Should().HaveCount(2);
```

**Comment by psibernetic** [comment]
Great stuff, thanks!
